services:
  grafana:
    user: root
    container_name: 'nominaltest-nominalds-datasource'

    build:
      context: ..
      dockerfile: .config/Dockerfile
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.3.0}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../dist:/var/lib/grafana/plugins/nominaltest-nominalds-datasource
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/nominaltest-nominalds-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.nominaltest-nominalds-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: nominaltest-nominalds-datasource
      # Admin credentials from .env
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      # Enable both anonymous and basic auth for flexibility
      GF_AUTH_BASIC_ENABLED: "true"
